[build] 
  publish = "public"

[build.processing.images]
  compress = true


[context.production] 
  command = "hugo -b https://www.ourmaninindia.com --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.110.0" 
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.development] 
  command = "hugo --gc --minify"
  
[context.development.environment]
  HUGO_VERSION = "0.110.0"
  NODE_ENV = "development"
  HUGO_ENABLEGITINFO = "true"


[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

  [plugins.inputs]
  # If it should show more verbose logs (optional, default = true)
  debug = true
  # Relative path to source directory in case you use Hugo's "--s" option
  # srcdir = "https://www.ourmaninindia.com"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404


## Cache Control
# Paste the below in https://play.netlify.com/headers to test
# Set max-age to 1 year (31536000 seconds) 
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"